serial:
  enabled: false
  port: "/dev/ttyCH341USB0"
  baudrate: 115200

binary:
  default_threshold: 253

circularity:
  default_threshold: 0.75  # 圆度阈值

filter:
  min_area: 50  # 最小面积
  max_area: 300  # 最大面积

offset:
  threshold: 5  # 容差

center:
  offset: 21  # 中心点偏移阈值