debug: true

mode: "dart"

camera:
  type: "opencv"
  id: 1

serial:
  enabled: false
  port: "/dev/ttyCH341USB0"
  baudrate: 115200

binary:
  default_threshold: 253

circularity:
  default_threshold: 0.75  # 圆度阈值

filter:
  min_area: 50  # 最小面积
  max_area: 300  # 最大面积

chassis_control:
  threshold: 5  # 容差

offset:
  center: 21  # 中心点偏移阈值
  dart_x: 0        # Dart模式用的 X 轴微调
  dart_y: 0        # Dart模式用的 Y 轴微调